weights: "models/LED/A/yolo/LED_color_mixing_best.pt"
exposure_time: "51170.0000"  # 20000 LED:200
gain: "23.0" #15
MV_CC_GetImageBuffer_nMsec: 10000
timeout: 1
width: 3072
height: 2048
enable_yolo: true
enable_anomalib: false
max_cache_size: 3
output_dir: "D:/Git/robotlearning/build_exe/Result"
