weights: "D:/Git/robotlearning/yolo11_inference/models/Cable1/A/yolo/best.pt"
device: cpu
conf_thres: 0.2
iou_thres: 0.45
imgsz:
- 640
- 640
timeout: 1
enable_yolo: true
output_dir: "D:/Git/robotlearning/build_exe/Result"
current_product: Cable1
expected_items:
  Cable1:
    A:
    - Red
    - Green
    - Orange
    - Yellow
    - Black
    - Black

pipeline:
  - color_check
  - count_check
  - sequence_check
  - save_results

steps:
  count_check:
    strict: true
  sequence_check:
    expected: [Red, Green, Orange, Yellow, Black, Black]
    direction: left_to_right

position_config:
  Cable1:
    A:
      enabled: false
      mode: bbox
      tolerance: 50
      expected_boxes:
        Orange:
          x1: 155
          y1: 322
          x2: 390
          y2: 436
        Red:
          x1: 96
          y1: 316
          x2: 334
          y2: 432
        Green:
          x1: 126
          y1: 319
          x2: 363
          y2: 432
        Black:
          x1: 210
          y1: 318
          x2: 475
          y2: 450
        Yellow:
          x1: 182
          y1: 320
          x2: 416
          y2: 440
      imgsz: 640


enable_color_check: true
color_checker_type: stats
color_model_path: "D:/Git/robotlearning/yolo11_inference/models/Cable1/A/yolo/color_stats.json"  # color_verifier summary JSON
