weights: "D:/Git/robotlearning/yolo11_inference/models/Cable1/A/yolo/best.pt"
device: cpu
conf_thres: 0.2
iou_thres: 0.45
imgsz:
- 640
- 640
timeout: 1
enable_yolo: true
output_dir: "D:/Git/robotlearning/build_exe/Result"
current_product: Cable1
expected_items:
  Cable1:
    A:
    - Black
    - Green
    - Orange
    - Red
    - Yellow

position_config:
  Cable1:
    A:
      enabled: false
      mode: bbox
      tolerance: 2
      expected_boxes:
        C22B: { x1: 350, y1: 210, x2: 390, y2: 310 }
        J5-1: { x1: 400, y1: 200, x2: 540, y2: 340 }
        J5-2: { x1: 80,  y1: 250, x2: 180, y2: 380 }
        J6:   { x1: 200, y1: 250, x2: 320, y2: 380 }
        J7:   { x1: 430, y1: 270, x2: 580, y2: 400 }

enable_color_check: true
color_checker_type: stats
color_model_path: "D:/Git/robotlearning/yolo11_inference/models/Cable1/A/yolo/color_stats.json"  # 由 color_verifier 產生的 summary JSON
